import logging

DOMAIN = "eob_wifi"
MANUFACTURER = "Elektrobock"
LOGGER = logging.getLogger(__name__)

BASE_SERVER_URL = "https://data.elektrobock.cz"
HISTORY_SERVER_URL = "https://history.elektrobock.cz"

API_LOGIN = "/api/Auth/login"
API_REGISTER = "/api/Auth/registerIdentity"
API_USER_UPDATE = "/api/User/update"
API_DEVICES_WITH_FCM = "/api/UsersDevices/withFcmData"
API_DEVICES_USERS = "/api/DevicesUsers"
API_PAIR_DEVICE = "/api/UserDevices/Register"
API_ADD_USER_DEVICE = "/api/UserDevices/AddUserToDeviceUsingPass"
API_DELETE_USER_DEVICE = "/api/UserDevices/Delete"
API_DEVICE = "/api/Device"
API_DEVICE_RENAME = "/api/Device/Rename"
API_DEVICE_FW_UPDATE = "/api/Device/UpdateFwStringTypeAndVariant"
API_FCM_LIST = "/api/Fcm/GetByUserDevicePair"
API_FCM_ADD = "/api/Fcm/AddToUserDevicePair"
API_FCM_DELETE = "/api/Fcm/DeleteFromUserDevicePair"
API_FORGOT_PSWD = "/api/UserEmail/forgotPswd"
API_CHANGE_PSWD = "/api/UserEmail/changePswd"

DEVICE_TYPE_PT32_WIFI = 0
DEVICE_TYPE_PT32_GSM = 1
DEVICE_TYPE_BPT725 = 2
DEVICE_TYPE_PHCJ37 = 3
DEVICE_TYPE_PHCJ39 = 4
DEVICE_TYPE_PHCJ38 = 5
DEVICE_TYPE_BT52W_OPT = 6
DEVICE_TYPE_U2 = 7
DEVICE_TYPE_TS11_WIFI = 8
DEVICE_TYPE_PT59 = 10
DEVICE_TYPE_GST_SOCKET = 11
DEVICE_TYPE_GSM_MODULE = 12
DEVICE_TYPE_PT41_MQTT = 13
DEVICE_TYPE_PT14 = 14
DEVICE_TYPE_PT14_WIF_ONLY = 20
DEVICE_TYPE_UNKNOWN = 255
DEVICE_TYPE_PT_THERMOSTAT = 256

DEVICE_TYPES_USED_IN_APP = [
    DEVICE_TYPE_TS11_WIFI,
    DEVICE_TYPE_PT14,
    DEVICE_TYPE_PT14_WIF_ONLY,
    DEVICE_TYPE_U2,
]

DEVICE_TYPE_NAMES = {
    DEVICE_TYPE_TS11_WIFI: "Ts11WiFi",
    DEVICE_TYPE_U2: "U2",
    DEVICE_TYPE_PT14: "Pt14",
    DEVICE_TYPE_PT14_WIF_ONLY: "Pt14WifOnly",
}

SUPPORTED_MODELS = ["TS11", "U2", "PT14", "PT14WIFONLY"]

DEVICE_TYPE_THERMOSTATS = [
    DEVICE_TYPE_TS11_WIFI,
    DEVICE_TYPE_U2,
]

DEVICE_TYPE_RELAYS = [
    DEVICE_TYPE_PT14,
    DEVICE_TYPE_PT14_WIF_ONLY,
]

TS11_VARIANT_NOT_SPECIFIED = 0
TS11_VARIANT_2MB = 1
TS11_VARIANT_4MB = 2
TS11_VARIANT_THERM = 3
TS11_VARIANT_CONSUMPTION = 4
TS11_VARIANT_THERM_PROFI = 5
TS11_VARIANT_EKO = 6
TS11_VARIANT_THERM_EKO = 8
TS11_VARIANT_PROFI_ESP32 = 9

CONF_USERNAME = "username"
CONF_PASSWORD = "password"

ATTR_DEVICE_ID = "device_id"
ATTR_DEVICE_TYPE = "device_type"
ATTR_FIRMWARE = "firmware"
ATTR_ADMIN_ID = "admin_id"
ATTR_DEVICE_VARIANT = "device_variant"
ATTR_IS_ANALOG_MODE = "isAnalogMode"


def _is_analog_mode(device: dict) -> bool:
    therm_data = device.get("thermData") or {}
    return bool(therm_data.get(ATTR_IS_ANALOG_MODE))

MODE_AUTO = "auto"
MODE_MANU = "manu"
MODE_OFF = "off"

MQTT_BROKER_HOST = "mqtt.elbock.cz"
MQTT_BROKER_PORT = 8081
MQTT_BROKER_WS_PATH = "/wss"
MQTT_KEEPALIVE = 60
MQTT_CLIENT_ID_PREFIX = "HA_"

TOPIC_BASE = {
    DEVICE_TYPE_TS11_WIFI: "TSWIFI",
    DEVICE_TYPE_PT14: "PTWIFI",
    DEVICE_TYPE_PT14_WIF_ONLY: "PTWIFI",
    DEVICE_TYPE_U2: "U2WIFI",
}

MSG_TYPE_MULTI_FIRST = 0x10
MSG_TYPE_MULTI_SECOND = 0x0A
MSG_TYPE_WRITE_OUTPUT_ON = (0x00, 0x01)
MSG_TYPE_WRITE_STATUS = (0x00, 0x02)
MSG_TYPE_WRITE_THERM_DATA = (0x10, 0x0B)
MSG_TYPE_RESPONSE_MULTI = (0x30, 0x0A)
MSG_TYPE_RESPONSE_STATUS = (0x30, 0x3C)
MSG_TYPE_RESPONSE_OUTPUT_STATE = (0x30, 0x30)
MSG_TYPE_RESPONSE_AUTO_MANU = (0x30, 0x31)
MSG_TYPE_RESPONSE_ERROR_UNKNOWN = (0x40, 0x02)
MSG_TYPE_RESPONSE_ERROR_WRONG = (0x40, 0x03)
